/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wyhw_plugin_JarEncryptUtil */

#ifndef _Included_com_wyhw_plugin_JarEncryptUtil
#define _Included_com_wyhw_plugin_JarEncryptUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wyhw_plugin_JarEncryptUtil
 * Method:    encrypt
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_wyhw_plugin_JarEncryptUtil_encrypt
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
